spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://anycompany-productiondb-instance-1.csjliovylmx5.us-west-1.rds.amazonaws.com:3306/ab3
    username: admin
    password: GrayGraph123#
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
server:
  tomcat:
    accesslog:
      enabled: true
      directory:  /var/log/application